from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
GENERATED_FILE = ROOT / "frontend" / "src" / "generated" / "codebaseSnapshot.ts"
EXCLUDED_PARTS = {".git", ".venv", "node_modules", "dist", ".pytest_cache", "__pycache__"}
TEXT_SUFFIXES = {".py", ".ts", ".tsx", ".css", ".html", ".md", ".svg", ".json", ".txt", ".yml", ".yaml"}


@dataclass(frozen=True)
class SnapshotBucket:
    label: str
    detail: str
    total_lines: int
    file_count: int


def is_excluded(path: Path) -> bool:
    return any(part in EXCLUDED_PARTS for part in path.parts)


def is_text_file(path: Path) -> bool:
    return path.suffix in TEXT_SUFFIXES


def count_lines(path: Path) -> int:
    with path.open("r", encoding="utf-8") as handle:
        return sum(1 for _ in handle)


def classify(relative_path: Path) -> str | None:
    path_string = relative_path.as_posix()

    if path_string == "frontend/index.html":
        return "front_prod"

    if path_string.startswith("frontend/src/"):
        if ".test." in relative_path.name or "test" in relative_path.parts:
            return "tests"
        if relative_path.suffix in {".ts", ".tsx", ".css"}:
            return "front_prod"

    if path_string.startswith("backend/app/tests/") and relative_path.suffix == ".py":
        return "tests"

    if path_string.startswith("backend/app/") and relative_path.suffix == ".py":
        return "back_prod"

    if path_string == "README.md":
        return "docs_static"

    if path_string.startswith("docs/") and relative_path.suffix == ".md":
        return "docs_static"

    if path_string.startswith("frontend/public/") and is_text_file(relative_path):
        return "docs_static"

    return None


def collect_snapshot() -> tuple[list[SnapshotBucket], SnapshotBucket]:
    buckets = {
        "front_prod": {"label": "前端生产代码", "detail": "React + Vite + TypeScript", "lines": 0, "files": 0},
        "back_prod": {"label": "后端生产代码", "detail": "FastAPI + SQLAlchemy", "lines": 0, "files": 0},
        "tests": {"label": "测试代码", "detail": "Vitest + Pytest 回归", "lines": 0, "files": 0},
        "docs_static": {"label": "文档与静态资源", "detail": "docs + README + public 资源", "lines": 0, "files": 0},
    }

    for path in ROOT.rglob("*"):
        if not path.is_file() or is_excluded(path):
            continue

        relative_path = path.relative_to(ROOT)
        bucket_key = classify(relative_path)
        if bucket_key is None:
            continue

        if not is_text_file(path):
            continue

        try:
            line_count = count_lines(path)
        except UnicodeDecodeError:
            continue

        buckets[bucket_key]["lines"] += line_count
        buckets[bucket_key]["files"] += 1

    snapshot = [
        SnapshotBucket(
            label=bucket["label"],
            detail=f"{bucket['files']} 个文件 · {bucket['detail']}",
            total_lines=bucket["lines"],
            file_count=bucket["files"],
        )
        for bucket in buckets.values()
    ]
    total_lines = sum(bucket.total_lines for bucket in snapshot)
    total_files = sum(bucket.file_count for bucket in snapshot)
    total_bucket = SnapshotBucket(
        label="当前快照总计",
        detail=f"{total_files} 个文件 · 生产代码 + 测试代码 + 文档/静态资源",
        total_lines=total_lines,
        file_count=total_files,
    )
    return snapshot, total_bucket


def format_lines(value: int) -> str:
    return f"{value:,} 行"


def render_typescript(snapshot: list[SnapshotBucket], total_bucket: SnapshotBucket) -> str:
    lines = [
        "// Generated by scripts/count_codebase_snapshot.py",
        "",
        "export const CODEBASE_SCOPE =",
        '  "统计范围：生产代码 + 测试代码 + 文档/静态资源；排除 .git、.venv、node_modules、dist 和缓存目录。";',
        "",
        "export const CODEBASE_SNAPSHOT = [",
    ]

    for bucket in snapshot:
        lines.append("  {")
        lines.append(f'    label: "{bucket.label}",')
        lines.append(f'    value: "{format_lines(bucket.total_lines)}",')
        lines.append(f'    detail: "{bucket.detail}",')
        lines.append("  },")

    lines.append("] as const;")
    lines.append("")
    lines.append("export const CODEBASE_TOTAL = {")
    lines.append(f'  label: "{total_bucket.label}",')
    lines.append(f'  value: "{format_lines(total_bucket.total_lines)}",')
    lines.append(f'  detail: "{total_bucket.detail}",')
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    snapshot, total_bucket = collect_snapshot()
    GENERATED_FILE.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(render_typescript(snapshot, total_bucket), encoding="utf-8")

    print(f"Wrote {GENERATED_FILE}")
    for bucket in snapshot:
        print(f"{bucket.label}: {format_lines(bucket.total_lines)} ({bucket.file_count} files)")
    print(f"{total_bucket.label}: {format_lines(total_bucket.total_lines)} ({total_bucket.file_count} files)")


if __name__ == "__main__":
    main()
